authors:
  ratseerofrattesse:
    name: RatseerOfRattesse
    description: Site owner and artist
    avatar: https://ratseerofrattesse.github.io/assets/img/misc/pfp.png
  idi0cy:
    name: idi0cy
    description: Science nerd that definitely isn't Technoblade reincarnate
    avatar: https://ratseerofrattesse.github.io/assets/img/misc/idi0cypfp.webp
  livingricecooker:
    name: LivingRiceCooker
    description: The Punmistress and the Narrative Goddess
    avatar: https://ratseerofrattesse.github.io/assets/img/misc/livingricecookerpfp.webp
  lamchops555:
    name: Lamchops555
    description: lamechops555
    avatar: https://ratseerofrattesse.github.io/assets/img/misc/lamchops555pfp.webp